#!/bin/bash
#
#***********************************************************************
#******************  CANADIAN ASTRONOMY DATA CENTRE  *******************
#*************  CENTRE CANADIEN DE DONNÉES ASTRONOMIQUES  **************
#
#  (c) 2016.                            (c) 2016.
#  Government of Canada                 Gouvernement du Canada
#  National Research Council            Conseil national de recherches
#  Ottawa, Canada, K1A 0R6              Ottawa, Canada, K1A 0R6
#  All rights reserved                  Tous droits réservés
#                                       
#  NRC disclaims any warranties,        Le CNRC dénie toute garantie
#  expressed, implied, or               énoncée, implicite ou légale,
#  statutory, of any kind with          de quelque nature que ce
#  respect to the software,             soit, concernant le logiciel,
#  including without limitation         y compris sans restriction
#  any warranty of merchantability      toute garantie de valeur
#  or fitness for a particular          marchande ou de pertinence
#  purpose. NRC shall not be            pour un usage particulier.
#  liable in any event for any          Le CNRC ne pourra en aucun cas
#  damages, whether direct or           être tenu responsable de tout
#  indirect, special or general,        dommage, direct ou indirect,
#  consequential or incidental,         particulier ou général,
#  arising from the use of the          accessoire ou fortuit, résultant
#  software.  Neither the name          de l'utilisation du logiciel. Ni
#  of the National Research             le nom du Conseil National de
#  Council of Canada nor the            Recherches du Canada ni les noms
#  names of its contributors may        de ses  participants ne peuvent
#  be used to endorse or promote        être utilisés pour approuver ou
#  products derived from this           promouvoir les produits dérivés
#  software without specific prior      de ce logiciel sans autorisation
#  written permission.                  préalable et particulière
#                                       par écrit.
#                                       
#  This file is part of the             Ce fichier fait partie du projet
#  OpenCADC project.                    OpenCADC.
#                                       
#  OpenCADC is free software:           OpenCADC est un logiciel libre ;
#  you can redistribute it and/or       vous pouvez le redistribuer ou le
#  modify it under the terms of         modifier suivant les termes de
#  the GNU Affero General Public        la “GNU Affero General Public
#  License as published by the          License” telle que publiée
#  Free Software Foundation,            par la Free Software Foundation
#  either version 3 of the              : soit la version 3 de cette
#  License, or (at your option)         licence, soit (à votre gré)
#  any later version.                   toute version ultérieure.
#                                       
#  OpenCADC is distributed in the       OpenCADC est distribué
#  hope that it will be useful,         dans l’espoir qu’il vous
#  but WITHOUT ANY WARRANTY;            sera utile, mais SANS AUCUNE
#  without even the implied             GARANTIE : sans même la garantie
#  warranty of MERCHANTABILITY          implicite de COMMERCIALISABILITÉ
#  or FITNESS FOR A PARTICULAR          ni d’ADÉQUATION À UN OBJECTIF
#  PURPOSE.  See the GNU Affero         PARTICULIER. Consultez la Licence
#  General Public License for           Générale Publique GNU Affero
#  more details.                        pour plus de détails.
#                                       
#  You should have received             Vous devriez avoir reçu une
#  a copy of the GNU Affero             copie de la Licence Générale
#  General Public License along         Publique GNU Affero avec
#  with OpenCADC.  If not, see          OpenCADC ; si ce n’est
#  <http://www.gnu.org/licenses/>.      pas le cas, consultez :
#                                       <http://www.gnu.org/licenses/>.
#
#  $Revision: 5 $
#
#***********************************************************************
#

## dynamically set the log level of a web service

CURL="curl --netrc"

function usage() {
    echo "usage cadcSetLog --get <URL>"
    echo "      cadcLogSet --set <URL> <level> [<package> [notrack]]"
    echo ""
    echo "     --get : get current log config"
    echo "     --set : set log config"
    echo "     URL   : URL to the LogControl resource (e.g. http://localhost/srv/logControl)"
    echo "     level : ERROR, WARN, INFO, DEBUG"
    echo "   package : (optional) package name (default: all currently configured packages get the specified level)"
    echo "   notrack : (optional) disable further tracking of this package"
    echo ""
    echo "Examples:"
    echo ""
    echo "1. increase log level of all configured packages to DEBUG:"
    echo "    cadcLogSet --set http://myServer/myApp/myLogControlServlet DEBUG"
    echo ""
    echo "2. increase log level of a specific package to DEBUG (adds it to list of configured packages):"
    echo "    cadcLogSet --set http://myServer/myApp/myLogControlServlet DEBUG my.package"
    echo ""
    echo "3. change log level of a specific package but not add it to list as in Example 1 and 2:"
    echo "    cadcLogSet --set http://myServer/myApp/myLogControlServlet INFO some.other.package notrack"
    echo ""
    echo "4. enable the Profiler class (recommend: notrack):"
    echo "    cadcLogSet --set http://myServer/myApp/myLogControlServlet INFO ca.nrc.cadc.profiler notrack"
    echo ""
    echo "5. disable the Profiler class (recommend: notrack):"
    echo "    cadcLogSet --set http://myServer/myApp/myLogControlServlet ERROR ca.nrc.cadc.profiler notrack"
}

## command-line args
ACTION=$1
URL=$2
LEVEL=$3
PKG=$4
DNT=$5

if [ -z $ACTION ]; then
    usage
    exit 1
fi

if [ -z $URL ]; then
    echo "error: missing URL"
    usage
    exit 1
fi

if [ $ACTION == "--get" ]; then
    if [ ! -z $LEVEL ]; then
        echo "error: extra arguments not usable by --get: $LEVEL $PKG"
        usage
        exit 1
    fi
elif [ $ACTION == "--set" ]; then
    if [ -z $LEVEL ]; then
        echo "error: missing level"
        usage
        exit 1
    fi

    CONTENT="level=$LEVEL"

    if [ ! -z $PKG ]; then
        CONTENT="${CONTENT}&package=${PKG}"
        if [ ! -z $DNT ]; then
            if [ $DNT == "notrack" ]; then
                CONTENT="${CONTENT}&notrack=1"
            fi
        fi
    fi
else
    usage
    exit 1
fi


## end: command-line args

if [ $ACTION == "--get" ]; then
    $CURL $URL
    exit $?
elif [ $ACTION == "--set" ]; then
    $CURL -d "${CONTENT}" $URL
    exit $?
fi
