# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11

    - name: build and test cadc-quality
      run: cd cadc-quality && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-util
      run: cd cadc-util && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-log
      run: cd cadc-log && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-rest
      run: cd cadc-rest && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-vodml
      run: cd cadc-vodml && ../gradlew --info clean build javadoc checkstyleMain install
      
    - name: build and test cadc-http-client
      run: cd cadc-http-client && ../gradlew --info clean build

    - name: build and test cadc-keygen
      run: cd cadc-keygen && ../gradlew --info clean build 
      
    
